---
title: "Tax Forecast Model"
author: "David T. Flynn, PhD"
date: "2026-03-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Library and Data Loading

Basic libraries for analysis. 

```{r libraries}
library(tidyverse)
library(fpp3)
library(dplyr)
library(urca)
library(feasts)
library(seasonal)
```

Start with the MW CPI data and the tax data. There will need to be some basic data descriptions and analysis before we do any forecasting.


```{r loading the data files}
tax_data <- read.csv("https://raw.githubusercontent.com/flynnecon/ndmodels/refs/heads/main/rawdata/ndtaxdata.csv")
cpi_data <- read.csv("https://raw.githubusercontent.com/flynnecon/ndmodels/refs/heads/main/rawdata/cpimw.csv")
tax_ts <- tax_data |> mutate(date=mdy(date)) |> mutate(date = yearmonth(date)) |> as_tsibble(index=date)
cpi_ts <- cpi_data |> mutate(date=mdy(date)) |> mutate(date = yearmonth(date)) |> as_tsibble(index=date)
taxcpi_ts <- inner_join(tax_ts,cpi_ts,by=c("date"))
```

```{r decomposition sales tax}
x11_dcmp_sales <- taxcpi_ts |> model(salestax_x11 = X_13ARIMA_SEATS(salestax ~ x11())) |> components()
autoplot(x11_dcmp_sales)
```

```{r decomposition total tax}
x11_dcmp_total <- taxcpi_ts |> model(totaltax_x11 = X_13ARIMA_SEATS(totaltax ~ x11())) |> components()
autoplot(x11_dcmp_total)
```

```{r unit root test}
taxcpi_ts |> features(salestax,unitroot_kpss)
x11_dcmp_sales |> features(trend,unitroot_kpss)
```



